HOST: http://localhost:8080/v1

--- Streetmix REST API
---
REST API for the [Streetmix](http://streetmix.net) application
---

--
User Authentication Resources
--

Sign-in a user, creating one if necessary.
POST /users
> Content-Type: application/json
> Accept: application/json
{
  "twitter": {
    "user_id": 8254163,
    "screen_name": "shaunak",
    "oauth_token": "fdy36ydgsjw0263bhd73181bdbe630eh033g28e=",
    "oauth_token_secret": "ue63tsbvjc92nvmdt268fnc0209e03yenc9371v383gr61u83r"
  }
}
< 201
< Content-Type: application/json
{
  "login_token": "906f7180-c4ba-11e2-8b8b-0800200c9a66"
}

Sign-out a user.
DELETE /users/{login_token}/login_token
< 204